# Generated by Django 2.2.10 on 2021-01-12 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, null=True, unique=True)),
                ('food_choice', models.IntegerField(choices=[(1, 'Rice and Beans'), (2, 'Fried Rice and Chicken'), (3, 'Bread and Beans'), (4, 'Pap and Akara')])),
                ('quantity', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Pending'), (2, 'Fulfilled')])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfilled_orders', to=settings.AUTH_USER_MODEL)),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_orders', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
